name = "tf47_echelon"
prefix = "tf47_echelon"
author = "Taskforce 47"
folder_optionals = false
files = [
    "mod.cpp",
    "LICENSE",
    "README.md"
]

key_name = "{{prefix}}-{{version}}"
authority = "{{version}}"

releasebuild = [
  "!copyInterceptPlugin"
]

[scripts.copyInterceptPlugin]
steps_linux = [
    "mkdir -p releases/{{version}}/@{{prefix}}/intercept",
    "cp build/lib64/* releases/{{version}}/@{{prefix}}/intercept"
]
steps_windows = [
    'xcopy build\lib64\* releases\\{{version}}\@{{prefix}}\intercept\ /Y /F'
]

show_output = true